# This file is only for testing the game service
# NOTE: The RPC_HOST environment variable is ignored because a RabbitMQ container is provided

services:
  rabbitmq:
    image: 'rabbitmq:latest'
    ports: 
      - '5672:5672'
      - '15672:15672'
  matchmaker:
    init: true
    env_file: .env
    build: .
    ports:
      - "8765:8765"
    volumes:
      - DEBUG_ONLY:/app
  game:
    init: true
    build: ../../gamev3
    ports:
      - ${PORT_RANGE}:${PORT_RANGE}
    environment:
      RPC_HOST: rabbitmq
      GAME_HOST: ${GAME_HOST}
      PORT_RANGE: ${PORT_RANGE}
      JWT_SECRET: ${JWT_SECRET}

volumes:
  DEBUG_ONLY:
    driver: local
    driver_opts:
      type: none
      device: /home/cgodecke/Desktop/Core/ft_transcendence/frontend_draft
      o: bind
