# This file is only for testing the game service
# NOTE: The RPC_HOST environment variable is ignored because a RabbitMQ container is provided

services:
  rabbitmq:
    image: 'rabbitmq:latest'
    ports: 
      - '5672:5672'
      - '15672:15672'
  matchmaker:
    init: true
    build: .
    ports:
      - "8765:8765"
    volumes:
      - DEBUG_ONLY:/app
  game:
    init: true
    build: ../gamev3
    ports:
      - ${PORT_RANGE}:${PORT_RANGE}
    environment:
      RPC_HOST: rabbitmq
      GAME_HOST: ${GAME_HOST}
      PORT_RANGE: ${PORT_RANGE}
      JWT_SECRET: ${JWT_SECRET}


  web:
    container_name: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      GAME_HOST: ${GAME_HOST}
    env_file:
      - .env
    depends_on: []
     

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./static:/code/static
    depends_on:
      - web
      - matchmaker
      - game
    
  
volumes:
  DEBUG_ONLY:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}
      o: bind
