# This file is only for testing the game service
# NOTE: The RPC_HOST environment variable is ignored because a RabbitMQ container is provided

networks:
  network:
    driver: bridge

services:
  rabbitmq:
    image: 'rabbitmq:latest'
    hostname: 'rabbitmq'
    ports: 
      - '5672:5672'
      - '15672:15672'
    networks:
      - network
    
  matchmaker:
    hostname: matchmaker
    init: true
    env_file: .env
    build: 
      context: .
      dockerfile: Dockerfile.matchmaker
    ports:
      - "8765:8765"
    volumes:
      - DEBUG_ONLY:/app
    networks:
      - network

  game:
    hostname: game
    init: true
    build: ../gamev3
    ports:
      - ${PORT_RANGE}:${PORT_RANGE}
    environment:
      RPC_HOST: rabbitmq
      GAME_HOST: ${GAME_HOST}
      PORT_RANGE: ${PORT_RANGE}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - network


  web:
    container_name: web
    hostname: web
    build: 
      context: .
      dockerfile: Dockerfile.web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - GAME_HOST=${GAME_HOST}
    env_file:
      - .env
    depends_on: []
    networks:
      - network
     

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./static:/code/static
    depends_on:
      - web
      - matchmaker
      - game
    networks:
      - network
    
  
volumes:
  DEBUG_ONLY:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}
      o: bind
