# Generated by Django 5.0.6 on 2024-06-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='id',
            new_name='game_id',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player1_score',
            new_name='p1_wins',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player2_score',
            new_name='p2_wins',
        ),
        migrations.RemoveField(
            model_name='game',
            name='loser',
        ),
    ]
