# Generated by Django 5.0.6 on 2024-06-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0002_remove_customuser_friends_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='match_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stats',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
