# Generated by Django 5.0.6 on 2024-06-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0003_customuser_last_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='popup_shown',
            field=models.BooleanField(default=False),
        ),
    ]
