# Generated by Django 4.2.13 on 2024-06-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0003_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='datetime',
            new_name='date',
        ),
    ]
