# Generated by Django 4.2.13 on 2024-06-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0005_rename_tournament_id_tournament_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(default='waiting', max_length=40),
        ),
    ]
