# Generated by Django 4.2.13 on 2024-06-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0007_alter_tournament_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='waiting', max_length=40),
        ),
    ]
